### ISSUE TITLE
Observation Timestamp

### ISSUE THREAD

**Issue by r4space** [landrs-toolkit/landrs-drone-TOAST#2]
Timestamp is currently a result not a time

**Comment by chrissweet** [comment]
So I have sosa:resultTime "http://www.w3.org/2001/XMLSchema#dateTime"^^rdf:type,
        "2020-07-03T18:03:44.013244"^^xsd:dateTimeStamp .

4.7.2.5 sosa:resultTime
IRI: http://www.w3.org/ns/sosa/resultTime
a OWL Datatype Property
result time - The result time is the instant of time when the Observation, Actuation or Sampling activity was completed. 
Domain Includes	sosa:Actuation, sosa:Observation, sosa:Sampling
Range	xsd:dateTime

Can you please clarify?

**Comment by chrissweet** [comment]
Fixed http://www.w3.org/2001/XMLSchema#dateTime"^^rdf:type so that, for example, sosa:hasResult [ a qudt-1-1:QuantityValue... . Timestamp types may change due to work here https://github.com/charlesvardeman/SOSA_K30sensor.
